// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract GhostNetAgent {
    struct Decision {
        bytes32 messageHash;
        string action;
        string resource;
        string priority;
        uint256 timestamp;
        bool isInitialized;
    }

    mapping(bytes32 => Decision) private decisions;

    event DecisionCreated(
        bytes32 indexed messageHash,
        string action,
        string resource,
        string priority,
        uint256 timestamp
    );

    /**
     * @dev Stores a decision generated by the AI Economic Agent.
     * @param messageHash Hash of the original emergency message.
     * @param action Recommended action text.
     * @param resource Allocated resource identifier.
     * @param priority Category priority level.
     */
    function storeDecision(
        bytes32 messageHash,
        string memory action,
        string memory resource,
        string memory priority
    ) public {
        require(!decisions[messageHash].isInitialized, "Decision already exists for this message hash");

        decisions[messageHash] = Decision({
            messageHash: messageHash,
            action: action,
            resource: resource,
            priority: priority,
            timestamp: block.timestamp,
            isInitialized: true
        });

        emit DecisionCreated(messageHash, action, resource, priority, block.timestamp);
    }

    /**
     * @dev Verifies if the local decision parameters match the on-chain recorded decision.
     */
    function verifyDecision(
        bytes32 messageHash,
        string memory action,
        string memory resource,
        string memory priority,
        uint256 timestamp
    ) public view returns (bool) {
        Decision memory d = decisions[messageHash];
        if (!d.isInitialized) {
            return false;
        }
        
        return (
            keccak256(abi.encodePacked(d.action)) == keccak256(abi.encodePacked(action)) &&
            keccak256(abi.encodePacked(d.resource)) == keccak256(abi.encodePacked(resource)) &&
            keccak256(abi.encodePacked(d.priority)) == keccak256(abi.encodePacked(priority)) &&
            d.timestamp == timestamp
        );
    }

    /**
     * @dev Gets decision details by message hash.
     */
    function getDecision(bytes32 messageHash) public view returns (Decision memory) {
        require(decisions[messageHash].isInitialized, "Decision does not exist");
        return decisions[messageHash];
    }
}
